name: asynchronous_programming
description: Asynchronous Programming code from Vandad Nahavandipoor's Tutorial
version: 1.0.0

environment:
  sdk: ^3.3.4

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
